apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: elasticsearch
  spec:
    tags:
    - annotations:
        docker.io/imported-from: elasticsearch:5.2.2
      from:
        kind: DockerImage
        name: elasticsearch:5.2.2
      generation: null
      importPolicy: {}
      name: 5.2.2
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: elasticsearch
  spec:
    replicas: 1
    selector:
      deploymentconfig: elasticsearch
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: elasticsearch
      spec:
        containers:
        - image: elasticsearch:5.2.2
          name: elasticsearch
          env: 
          - name: xpack.security.enabled
            value: false
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
          ports:
          - containerPort: 9200
          resources: {}
          livenessProbe:
            httpGet:
              path: /elasticsearch
              port: 9200
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - elasticsearch
        from:
          kind: ImageStreamTag
          name: elasticsearch:5.2.2
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: elasticsearch
  spec:
    ports:
    - name: 9200-tcp
      port: 9200
      targetPort: 9200
    selector:
      deploymentconfig: elasticsearch
  status:
    loadBalancer: {}
kind: List
metadata: {}

