apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: rabbitmq
  spec:
    tags:
    - annotations:
        docker.io/imported-from: rabbitmq:3-management
      from:
        kind: DockerImage
        name: rabbitmq:3-management
      generation: null
      importPolicy: {}
      name: 3-management
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: rabbitmq
  spec:
    replicas: 1
    selector:
      deploymentconfig: rabbitmq
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: rabbitmq
      spec:
        containers:
        - image: rabbitmq:3-management
          name: rabbitmq
          ports:
          - containerPort: 5672
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - rabbitmq
        from:
          kind: ImageStreamTag
          name: rabbitmq:3-management
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: rabbitmq
  spec:
    ports:
    - name: 5672-tcp
      port: 5672
      targetPort: 5672
    selector:
      deploymentconfig: rabbitmq
  status:
    loadBalancer: {}
kind: List
metadata: {}

